### ISSUE TITLE
Many Chrome Extension Missing

### ISSUE THREAD

**Issue by ishu3101** [mdamien/chrome-extensions-archive#1]
Your crawler appears to be missing many of the chrome extension available on the chrome web store.

For example: none of my chrome extension are showing on your website.
[Copy URL + Title](https://chrome.google.com/webstore/detail/copy-url-%20-title/dgagjmdgbakclelfacghmmbadkdegjjh)
[Gist It](https://chrome.google.com/webstore/detail/gist-it/gmemoangmfinnplfifcjjdfeapdfgjkg)

**Comment by mdamien** [comment]
There's 88709 extensions/apps/themes in the webstore, I aim currently for the top 20k (today I have 16,923).

Your first one is there (you just have to wait for the page to load completely since it's progressive).
You second one is gonna be archived later.

I should make this clear somewhere, thanks for the bug report.

**Comment by ishu3101** [comment]
I don't see my first one. I have waited for the page to load completely. Doing a search on the page using  `ctrl + f` also does not find my first extension.

**Comment by mdamien** [comment]
You're right, it's archived on my disk but not shown on the website. Let me take a deeper look and I will be back.

**Comment by mdamien** [comment]
@ishu3101 I updated the website and now there's 80k+ extensions displayed. Here's the link to yours: http://dam.io/chrome-extensions-archive/pages/3.html#dgagjmdgbakclelfacghmmbadkdegjjh.

Only thing is that I'm switching to another hosting solution for the .crx so 99% of them aren't available right now.

**Comment by ishu3101** [comment]
Thanks. Where can I find my second extension? Also, what would the chrome extension archive be used for? Why are you switching to another host?

**Comment by mdamien** [comment]
The second one is here: http://dam.io/chrome-extensions-archive/pages/11.html#gmemoangmfinnplfifcjjdfeapdfgjkg

The goals and plans for the project are detailed in the readme. For the hosting, Google Cloud Storage is costing me 100 times more than self-hosting on a cheap vps.

**Comment by mdamien** [comment]
Closing this since I think it's fixed, don't hesitate to re-open if you think it's not.
