### ISSUE TITLE
JSON of aggregated data?

### ISSUE THREAD

**Issue by MikeeI** [mdamien/chrome-extensions-archive#10]
Hi. Great project.

How about a json file with the aggregated data that you display white on dark grey on the extension page https://crx.dam.io/ext/chfdnecihphmhljaaejmgoiahnihplgn.html.

It looks like json but got some errors.

Greetings

**Comment by mdamien** [comment]
Hi, yup, it was a python `pprint`, changed it to json now, thanks for the report :+1:
