### ISSUE TITLE
Curious about hosting costs

### ISSUE THREAD

**Issue by krackers** [mdamien/chrome-extensions-archive#20]
Hey this is a pretty neat service.

I was just wondering roughly how much it costs per month to host this (since I see you don't have any ads).

I'm guessing since you only store top 20k, extension sizes are small, and updates can be stored as deltas the physical space used won't be too much, maybe on the order of 100 Gigs or so.

Also, since the built website is static, the main cost will be from scraping and processing extension pages. 

---

Also, how were you able to discover the sitemap url for the chrome webstore? I thought about doing a similar service a few years back but gave up when I thought there was no way to programmatically get a list of extensions without using a full headless browser instance.

(Incidentally, doesn't google rate limit requests? How were you able to work around that?)

**Comment by mdamien** [comment]
it's costing me 16€/month, i'm on a ovh kimsufi (1 To)
