### ISSUE TITLE
For all extensions on the web?

### ISSUE THREAD

**Issue by Pacerier** [mdamien/chrome-extensions-archive#21]
Is this only for archiving "your" extension or does it work for all extensions across the web?

How do you manage storage then?

**Comment by mdamien** [comment]
it's only archiving public extensions on the chrome web store for now. I store them on the same server serving crx.dam.io, thank to OVH :)

**Comment by Pacerier** [comment]
But that's a lot of data isn't it? And what about the bandwidth cost?

**Comment by mdamien** [comment]
Bandwidth is free with ovh :smiley:
