### ISSUE TITLE
popup width problem

### ISSUE THREAD

**Issue by YumeStudioIT** [mdamien/chrome-extensions-archive#24]
![translator](https://user-images.githubusercontent.com/3143960/27334410-842427e6-55c9-11e7-96a9-a3d92a8631f8.jpg)

I don't know what happens but the pop-up windows change and now is too small to be useful, I try manually but only height change.
There is a way to fix it? maybe a css file?
thanks for helping

**Comment by mdamien** [comment]
Sorry but you must report it to the extension and not to the archive, thanks.
