### ISSUE TITLE
search bar

### ISSUE THREAD

**Issue by willman604** [mdamien/chrome-extensions-archive#27]
there needs to be a search bar please

**Comment by mdamien** [comment]
This can be done via Google search or the web store search but I keep it in mind

EDIT: and taking the ID in the url and doing crx.dam.io/ext/ID.html

**Comment by mdamien** [comment]
I've made the listings more compact, they each have 50k items. Meaning, it should just take one or two Ctrl-F to find the extension you're looking for.
