### ISSUE TITLE
Extension removed from Chrome web store

### ISSUE THREAD

**Issue by RobertAb1** [mdamien/chrome-extensions-archive#28]
I have noticed that extension Native Lazy Tabs was removed from Chrome web store. Also I am getting the following message in   _chrome://extensions/_ 
"This extension violates the Chrome Web Store policy"
Also see this comment and below: 
https://www.ghacks.net/2017/06/02/speed-up-chrome-start-by-lazy-loading-tabs/#comment-4310212

What has happened? Why did they block your extension?

**Comment by mdamien** [comment]
Hi, it's not my extension, crx.dam.io only host an archive of the sources.

You can find you extension here if you wish to re-install it: https://crx.dam.io/ext/ianooggapgmmmfojacmhnfaheidgpbki.html
