### ISSUE TITLE
letsencrypt cert expired

### ISSUE THREAD

**Issue by GottZ** [mdamien/chrome-extensions-archive#32]
FYI

**Comment by mdamien** [comment]
Thanks, fixed it :) My conclusion is that I should migrate to a self-signed certificate

**Comment by GottZ** [comment]
you should just run certbot as a cronjob and automate the certificate issue. if you are using nginx you could even use the certbot nginx plugin and don't even need to reload your nginx configuration upon receiving new certs :)

**Comment by GottZ** [comment]
just look at this: https://certbot.eff.org/docs/using.html
