### ISSUE TITLE
Demo site SSL is expired

### ISSUE THREAD

**Issue by Hashim-mansoor** [mdamien/chrome-extensions-archive#36]
Hi
Can you please fix your demo site SSL, looks like its expired - Thanks

**Comment by Linden10** [comment]
Yeah same, I'm unable to browse your site with opera as the it deems
my connection not private due to the expired ssl security certificate.

This the site I'm referring to btw:
https://crx.dam.io/

Hope you can resolve this issue without too much trouble! ^^

**Comment by mdamien** [comment]
Thanks, I think this SSL expiration make it clear the website is not noob-friendly and it's for experienced users. I should self-sign it but I like this situation, I have less desperate emails of lost people now :)

**Comment by fletom** [comment]
experienced user here, but not able to access the site with Chrome because there doesn't seem to be a way to bypass the error anymore

any chance of a fix, or an unencrypted HTTP version?

**Comment by mdamien** [comment]
@fletom I've renewed the certificate for now after many complaints, this issue is fixed :tada:  :tada:  :tada:  :tada:  :tada:

**Comment by fletom** [comment]
thank you very much!
